### ISSUE TITLE
RuntimeError with 1.03, iterm 3.0.12

### ISSUE THREAD

**Issue by eric-hu** [achiu/consular-iterm#16]
```
/Users/erichu/.gem/ruby/2.3.3/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:676:in `rescue in method_missing': Unknown property, element or command: 'current_terminal' (RuntimeError)
```

The backtrace includes:

```
from /Users/erichu/.gem/ruby/2.3.3/gems/consular-iterm-1.0.3/lib/consular/iterm.rb:57:in `process!'
```

I found that there's a difference between the current master branch and 1.0.3.  This error goes away when I uninstall and run `rake install` from master.  Perhaps the current master branch should be bumped to 1.0.4 or 1.0.4-rc?

**Comment by eric-hu** [comment]
This is irrelevant if PR #17 is merged.
